plugins:
  - jekyll-seo-tag

title: Dinda Tisi Calista
author: Dinda Tisi Calista

twitter:
  username: dindatisi

social:
  name: Dinda Tisi Calista
  links:
    - https://twitter.com/dindatisi
    - https://www.facebook.com/dindatisicalista
    - https://www.linkedin.com/in/dindatc
    - https://github.com/dindatisi
    - https://dindatc.wordpress.com
    - https://medium.com/dindatc
    - https://instagram.com/dindatisi
